project:
  type: book
book:
  title: Introduction to Human Biology Laboratory Workbook
  author:
  - name: George Mateja
    affiliations:
      - The Community College of Baltimore County
  date: "2026"
  chapters:
    - index.qmd
    - toc.qmd
    - Front_Matter_1_Scientific_Writing,_Citations,_and_Using_Credible_Sources.qmd
    - Front_Matter_2_PRE-LAB_PREPARATION_AND_RESPONSIBLE_USE_OF_AI.qmd
    - Laboratory_Exercise_01_Metrics_and_Measurements_Safety_Dundalk_Version.qmd
format:
  html:
    theme:
      - cosmo
      - brand
