project:
  type: book
book:
  title: Introduction to Human Biology Laboratory Workbook
  author:
  - name: George Mateja
    affiliations:
      - The Community College of Baltimore County
  date: "2026"
  repo-url: https://github.com/maptv/lab
  downloads: [pdf, epub, docx]
  chapters:
    - index.qmd
    - toc.qmd
    - Front_Matter_1_Scientific_Writing,_Citations,_and_Using_Credible_Sources.qmd
    - Front_Matter_2_PRE-LAB_PREPARATION_AND_RESPONSIBLE_USE_OF_AI.qmd
    - Laboratory_Exercise_01_Metrics_and_Measurements_Safety_Dundalk_Version.qmd
    - Laboratory_Exercise_02_Use_of_the_Microscope.qmd
    - Laboratory_Exercise_03_Molecules_Water_and_pH.qmd
    - Laboratory_Exercise_04_Chemical_Composition_of_Cells_VM.qmd
    - Laboratory_Exercise_04_Take_Home_Molecular_Structure_of_Biological_Macromolecules.qmd
    - Laboratory_Exercise_05_Diffusion,_Osmosis_and_the_Cell.qmd
    - Laboratory_Exercise_06_Enzyme_activity_lab_Turnip_peroxidase_Vernier_modified_Dundalk.qmd
    - Laboratory_Exercise_08_Respiration_and_Yeast_Fermentation.qmd
    - Laboratory_Exercise_09_Photosynthesis_Respiration.qmd
    - Laboratory_Exercise_11_Mendelian_Genetics_in_Corn_and_Chi_Square_Testing.qmd
    - Laboratory_Exercise_12_Introduction_to_Mendelian_Genetics.qmd
format:
  html:
    theme:
      light: [cosmo, brand]
      dark: [darkly, brand]
  pdf: default
  epub: default
  docx: default
