project:
  type: book
book:
  title: Introduction to Human Biology Laboratory Workbook
author:
  author: George Mateja
  affiliation: The Community College of Baltimore County
  version: 4
  date: 2024
  chapters:
    - chapters/ack.qmd
    - chapters/01.qmd
    - chapters/02.qmd
    - chapters/03.qmd
    - chapters/04.qmd
    - chapters/05.qmd
    - chapters/06.qmd
    - chapters/07.qmd
    - chapters/08.qmd
    - chapters/09.qmd
    - chapters/10.qmd
    - chapters/11.qmd
    - chapters/12.qmd
    - chapters/13.qmd
    - chapters/14.qmd
    - chapters/15.qmd
    - chapters/16.qmd
    - chapters/17.qmd
    - chapters/18.qmd
    - chapters/19.qmd
    - chapters/20.qmd
    - chapters/21.qmd
    - chapters/22.qmd
    - chapters/23.qmd
    - chapters/att.qmd
bibliography: references.bib
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
